# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 471)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("*{\n"
"    border:none;    \n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    \n"
"}\n"
"\n"
"#centralwidget{\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"#nav{\n"
"    background-color: #3454CF\n"
"}\n"
"\n"
"#logo{\n"
"    color: #fff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nav = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nav.sizePolicy().hasHeightForWidth())
        self.nav.setSizePolicy(sizePolicy)
        self.nav.setMaximumSize(QtCore.QSize(16777215, 70))
        self.nav.setObjectName("nav")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.nav)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logoContainer = QtWidgets.QWidget(self.nav)
        self.logoContainer.setMaximumSize(QtCore.QSize(16777215, 16777173))
        self.logoContainer.setObjectName("logoContainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.logoContainer)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLogo = QtWidgets.QPushButton(self.logoContainer)
        self.btnLogo.setMaximumSize(QtCore.QSize(50, 50))
        self.btnLogo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo/warehouse-solid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogo.setIcon(icon)
        self.btnLogo.setIconSize(QtCore.QSize(40, 30))
        self.btnLogo.setObjectName("btnLogo")
        self.horizontalLayout.addWidget(self.btnLogo)
        self.logoText = QtWidgets.QLabel(self.logoContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoText.sizePolicy().hasHeightForWidth())
        self.logoText.setSizePolicy(sizePolicy)
        self.logoText.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.logoText.setFont(font)
        self.logoText.setAutoFillBackground(False)
        self.logoText.setStyleSheet("#logoText{\n"
"    color: #fff\n"
"}")
        self.logoText.setObjectName("logoText")
        self.horizontalLayout.addWidget(self.logoText)
        self.horizontalLayout_2.addWidget(self.logoContainer)
        self.verticalLayout.addWidget(self.nav)
        self.containerBody = QtWidgets.QWidget(self.centralwidget)
        self.containerBody.setMaximumSize(QtCore.QSize(16777215, 401))
        self.containerBody.setObjectName("containerBody")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.containerBody)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sideNav = QtWidgets.QWidget(self.containerBody)
        self.sideNav.setMaximumSize(QtCore.QSize(231, 16777215))
        self.sideNav.setStyleSheet("#sideNav{\n"
"    background-color: #3454CF\n"
"}\n"
"\n"
"#menu1 QPushButton{\n"
"    color: #fff;\n"
"    text-align: left;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"#menu2 QPushButton{\n"
"    color: #fff;\n"
"    text-align: left;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.sideNav.setObjectName("sideNav")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sideNav)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menu1 = QtWidgets.QFrame(self.sideNav)
        self.menu1.setMaximumSize(QtCore.QSize(16777215, 233))
        self.menu1.setStyleSheet("#btnDashboard{\n"
"    border: 2px solid #fff;\n"
"    border-radius: 4px;\n"
"}")
        self.menu1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu1.setObjectName("menu1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menu1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnDashboard = QtWidgets.QPushButton(self.menu1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDashboard.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("logo/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDashboard.setIcon(icon1)
        self.btnDashboard.setObjectName("btnDashboard")
        self.verticalLayout_3.addWidget(self.btnDashboard)
        self.btnItems = QtWidgets.QPushButton(self.menu1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnItems.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("logo/items.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnItems.setIcon(icon2)
        self.btnItems.setObjectName("btnItems")
        self.verticalLayout_3.addWidget(self.btnItems)
        self.btnStorage = QtWidgets.QPushButton(self.menu1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnStorage.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("logo/storage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStorage.setIcon(icon3)
        self.btnStorage.setObjectName("btnStorage")
        self.verticalLayout_3.addWidget(self.btnStorage)
        self.btnInbound = QtWidgets.QPushButton(self.menu1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnInbound.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("logo/inbound.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInbound.setIcon(icon4)
        self.btnInbound.setObjectName("btnInbound")
        self.verticalLayout_3.addWidget(self.btnInbound)
        self.btnOutbound = QtWidgets.QPushButton(self.menu1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnOutbound.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("logo/outbound.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOutbound.setIcon(icon5)
        self.btnOutbound.setObjectName("btnOutbound")
        self.verticalLayout_3.addWidget(self.btnOutbound)
        self.verticalLayout_2.addWidget(self.menu1)
        spacerItem = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem)
        self.menu2 = QtWidgets.QFrame(self.sideNav)
        self.menu2.setMaximumSize(QtCore.QSize(16777215, 47))
        self.menu2.setStyleSheet("")
        self.menu2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu2.setObjectName("menu2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menu2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnLogout = QtWidgets.QPushButton(self.menu2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnLogout.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("logo/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogout.setIcon(icon6)
        self.btnLogout.setObjectName("btnLogout")
        self.verticalLayout_4.addWidget(self.btnLogout)
        self.verticalLayout_2.addWidget(self.menu2)
        self.horizontalLayout_3.addWidget(self.sideNav)
        self.mainContent = QtWidgets.QWidget(self.containerBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainContent.sizePolicy().hasHeightForWidth())
        self.mainContent.setSizePolicy(sizePolicy)
        self.mainContent.setMaximumSize(QtCore.QSize(577, 402))
        self.mainContent.setStyleSheet("#mainContent{\n"
"    background-color: #808080\n"
"}")
        self.mainContent.setObjectName("mainContent")
        self.horizontalLayout_3.addWidget(self.mainContent)
        self.verticalLayout.addWidget(self.containerBody)
        self.containerBody.raise_()
        self.nav.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logoText.setText(_translate("MainWindow", "WMS"))
        self.btnDashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btnItems.setText(_translate("MainWindow", "Items"))
        self.btnStorage.setText(_translate("MainWindow", "Storage"))
        self.btnInbound.setText(_translate("MainWindow", "Inbound"))
        self.btnOutbound.setText(_translate("MainWindow", "Outbound"))
        self.btnLogout.setText(_translate("MainWindow", "Logout"))
from . import _icons_rc
